import { test, expect } from './fixtures.mjs'
import { openTodos, addBox, dayStr, ignoreErrs, row } from './helpers/todos.mjs'

test('open from the sidebar row and menu shortcut; add, reject blank, no duplicate on double Enter', async ({ grain }) => {
  const { page } = grain
  await openTodos(page)
  await expect(page.getByText('Nothing open')).toBeVisible()
  await addBox(page).fill('   ')
  // The Add button only appears once there is something to add.
  await expect(page.getByRole('button', { name: 'Add', exact: true })).toHaveCount(0)
  await addBox(page).press('Enter')
  expect(await grain.api('/todos')).toHaveLength(0)
  await addBox(page).fill('Buy milk')
  await addBox(page).press('Enter'); await addBox(page).press('Enter')
  await expect(page.locator('.todo')).toHaveCount(1)
  await expect(addBox(page)).toHaveValue('')
  await page.waitForTimeout(500)
  expect(await grain.api('/todos')).toHaveLength(1)
  await addBox(page).fill('Walk dog')
  await page.getByRole('button', { name: 'Add', exact: true }).dblclick()
  await expect(page.locator('.todo')).toHaveCount(2)
  await page.waitForTimeout(500)
  expect(await grain.api('/todos')).toHaveLength(2)
  await page.getByRole('button', { name: 'Calendar', exact: true }).first().click()
  await expect(page.getByPlaceholder('Add to Todos…')).toHaveCount(0)
  await grain.app.evaluate(({ Menu }) => {
    const find = (items) => { for (const i of items) { if (i.label === 'Lists' && i.accelerator === 'CmdOrCtrl+2') return i; const r = i.submenu && find(i.submenu.items); if (r) return r } }
    find(Menu.getApplicationMenu().items).click()
  })
  await expect(page.getByPlaceholder('Add to Todos…')).toBeVisible()
  expect(ignoreErrs(grain.consoleErrors)).toEqual([])
})

test('huge title (10 KB) is stored whole and does not break layout', async ({ grain }) => {
  const { page } = grain
  await openTodos(page)
  await addBox(page).fill('x'.repeat(10_000))
  await addBox(page).press('Enter')
  await expect(page.locator('.todo')).toHaveCount(1)
  const t = await grain.api('/todos')
  expect(t[0].title.length).toBe(10_000)
  const sw = await page.evaluate(() => document.querySelector('.page-body').scrollWidth - document.querySelector('.page-body').clientWidth)
  expect(sw).toBeLessThanOrEqual(1)
  expect(ignoreErrs(grain.consoleErrors)).toEqual([])
})

test('complete / reopen, inline edit Enter saves and Esc cancels, delete', async ({ grain }) => {
  const { page } = grain
  await grain.api('/todos', { method: 'POST', body: { title: 'Alpha' } })
  await openTodos(page)
  await page.getByRole('button', { name: 'Complete: Alpha' }).click()
  await expect(page.locator('.todo')).toHaveCount(0)
  await expect.poll(async () => (await grain.api('/todos?include_done=true'))[0].done).toBeTruthy()
  await page.getByText('Show done').click()
  await expect(row(page, 'Alpha')).toHaveClass(/done/)
  await page.getByRole('button', { name: 'Reopen: Alpha' }).click()
  await expect(row(page, 'Alpha')).not.toHaveClass(/done/)
  await page.getByText('Alpha', { exact: true }).click()
  await page.getByLabel('Todo title').fill('Beta')
  await page.getByLabel('Todo title').press('Enter')
  await expect(page.getByText('Beta', { exact: true })).toBeVisible()
  await page.getByText('Beta', { exact: true }).click()
  await page.getByLabel('Todo title').fill('Gamma')
  await page.getByLabel('Todo title').press('Escape')
  await expect(page.getByText('Beta', { exact: true })).toBeVisible()
  expect((await grain.api('/todos'))[0].title).toBe('Beta')
  await page.getByText('Beta', { exact: true }).click()
  await page.getByLabel('Todo title').fill('  ')
  await page.getByLabel('Todo title').press('Enter')
  await expect(page.getByText('Beta', { exact: true })).toBeVisible()
  await page.getByText('Beta', { exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Todo title')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Delete todo: Beta' }).click()
  await expect(page.locator('.todo')).toHaveCount(0)
  expect(await grain.api('/todos?include_done=true')).toHaveLength(0)
  expect(ignoreErrs(grain.consoleErrors)).toEqual([])
})

test('due date set/clear and sections incl. overdue styling', async ({ grain }) => {
  const { page } = grain
  await grain.api('/todos', { method: 'POST', body: { title: 'Late one', due: dayStr(-3) } })
  await grain.api('/todos', { method: 'POST', body: { title: 'Now one', due: dayStr(0) } })
  await grain.api('/todos', { method: 'POST', body: { title: 'Soon one', due: dayStr(5) } })
  await grain.api('/todos', { method: 'POST', body: { title: 'Some one' } })
  await openTodos(page)
  for (const h of ['Overdue', 'Today', 'Upcoming', 'Someday']) await expect(page.locator('h4.section-h', { hasText: h })).toBeVisible()
  const cls = await row(page, 'Late one').locator('.todo-due').getAttribute('class')
  expect(cls).toMatch(/overdue|late|danger|red/)
  await page.getByLabel('Due date for Some one').fill(dayStr(2))
  await expect.poll(async () => (await grain.api('/todos')).find((t) => t.title === 'Some one').due).toBe(dayStr(2))
  await page.getByLabel('Due date for Some one').fill('')
  await expect.poll(async () => (await grain.api('/todos')).find((t) => t.title === 'Some one').due).toBeNull()
  await page.getByRole('button', { name: 'Due date, priority, repeat' }).click()
  await page.getByLabel('Due date (optional)').fill(dayStr(1))
  await addBox(page).fill('With due'); await addBox(page).press('Enter')
  await expect.poll(async () => (await grain.api('/todos')).find((t) => t.title === 'With due')?.due).toBe(dayStr(1))
  expect(ignoreErrs(grain.consoleErrors)).toEqual([])
})
